import images from "./Images";
import { categoryFilter } from "../utils/filter";

export const CommunityPostData = [
  {
    id: 1,
    category: "disease",
    smallCategory: "백점병",
    title: "이거 백점병인가요?",
    content:
      "구피항에 있는 구피들 몸에 점들이 점점 많아지고 있어요.. 환공포증 날 것 같은데 이거 도대체 왜 이러는 건가요? 찾아보니 백점병이라고 하더라구요 ㅜㅜ",
    writer: "김기성",
    imgUrl: images.communityImg1,
    date: "01/03",
    howLong: "3주전",
    comment: "3",
    heart: "1",
  },
  {
    id: 2,
    category: "disease",
    smallCategory: "백점병",
    title: "물고기들 몸에 흰점들이 일어나요",
    content:
      "일주일 전에 이마트에서 입양한 아이들입니다. 그런데 엊그제부터 갑자기 흰점들이 나타나더니 기력이 없어지네요.. 이거 무슨 병인가요?",
    writer: "김장훈",
    imgUrl: images.communityImg2,
    date: "01/01",
    howLong: "3주전",
    comment: "2",
    heart: "5",
  },
  {
    id: 3,
    category: "disease",
    smallCategory: "배마름병",
    title: "갑자기 배가 홀쭉해졌어요",
    content:
      "물고기들이 밥은 먹는 것 같더니.. 갑자기 2일 전부터 먹지 않다가 이제는 아예 배가 쏙 들어갔어요. 이거 배마름병이라고도 하던데 진짜 배마름병인건가요? 답변 부탁드립니다 ㅠㅠ!",
    writer: "이민영",
    imgUrl: images.communityImg3,
    date: "01/11",
    howLong: "2주전",
    comment: "3",
    heart: "1",
  },
  {
    id: 4,
    category: "disease",
    smallCategory: "백점병",
    title: "환공포증 생길 것 같아요..",
    content:
      "환공포증 생길 것 같습니다 ㅜ 어제 한 두마리가 몸에 반점이 생기더니 이제는 완전히 잠식되었어요.. 어항에 있는 모든 물고기 몸이 다 이렇습니다 ㅜ 이거 원래 이런 건가요? 분리시켰는데도 계속 이럽니다..",
    writer: "배지호",
    imgUrl: images.communityImg4,
    date: "12/24",
    howLong: "1달전",
    comment: "1",
    heart: "5",
  },
  {
    id: 5,
    category: "disease",
    smallCategory: "배마름병",
    title: "배마름병 맞나요?",
    content:
      "어제부터 기력이 없더니 이제는 완전히 땅에 누워있네요.. 배가 좀 들어간 것 같은데 배마름병인지 아닌지 솔직히 잘모르겠습니다",
    writer: "김승훈",
    imgUrl: images.communityImg5,
    date: "12/22",
    howLong: "1달전",
    comment: "1",
    heart: "3",
  },
  {
    id: 6,
    category: "filter",
    smallCategory: "녹조",
    title: "녹조 현상이 너무 심해요",
    content:
      "녹조 현상이 너무 심해요. 이끼잡이 물고기나 새우들 넣어야할까요? 고수님들 답변 부탁드립니다!",
    writer: "김호준",
    imgUrl: images.communityImg6,
    date: "01/02",
    howLong: "3주전",
    comment: "1",
    heart: "3",
  },
  {
    id: 7,
    category: "breeding",
    smallCategory: "물잡이",
    title: "어항 셋팅 기간이 궁금합니다",
    content:
      "이번에 2자반 어항으로 셋팅하려고 하는데.. 물잡이 기간이 얼마나 소요될까요? 최대한 빨리 투입하고 싶은 마음이지만 최소 2주는 기다려야한다고 말해서요",
    writer: "정하준",
    imgUrl: images.communityImg7,
    date: "01/02",
    howLong: "3주전",
    comment: "2",
    heart: "5",
  },
  {
    id: 8,
    category: "goods",
    smallCategory: "수조",
    title: "하스타투스 40마리 어항 사이즈 문의합니다",
    content:
      "하스타투스 40마리 투입해서 군영효과 좀 보려고 하는데요! 40마리정도면 몇자 어항이 필요할까요? 2자로도 군영을 볼 수 있는 지 궁금합니다!",
    writer: "박민재",
    imgUrl: images.communityImg8,
    date: "01/05",
    howLong: "3주전",
    comment: "1",
    heart: "4",
  },
  {
    id: 9,
    category: "species",
    smallCategory: "열대어",
    title: "풀레드 구피 진짜 이쁘네요",
    content:
      "인기 많은 어종으로 유명하기는 하지만, 그래도 실제로 어항 셋팅하고 입수하니 더 이쁜 것 같아요. 입양 적극 추천합니다 !!",
    writer: "김민정",
    imgUrl: images.communityImg9,
    date: "01/12",
    howLong: "2주전",
    comment: "12",
    heart: "9",
  },
  {
    id: 10,
    category: "board",
    smallCategory: "일상",
    title: "나른한 주말 어항 구경하고 가세요!",
    content:
      "휴일에는 집에서 물멍 때리는 게 좋네요~ 간단한 디스커스항으로 꾸며놓으니 아프리카 호수에서 주말을 보내는 것 같기도 하고 ㅋㅋ 좋네요.",
    writer: "이명숙",
    imgUrl: images.communityImg10,
    date: "01/13",
    howLong: "2주전",
    comment: "1",
    heart: "11",
  },
];

export const CategoryData = [
  "all",
  "disease",
  "filter",
  "breeding",
  "goods",
  "species",
  "board",
  "column",
];

export const SmallCategoryData: { [key: string]: string[] } = {
  disease: ["전체", "백점병", "배마름병", "솔방울병", "기타"],
  filter: ["전체", "녹조", "백탁현상", "비린내", "기타"],
  breeding: ["전체", "물잡이", "합사", "기타"],
  goods: ["전체", "수조", "여과기", "히터", "조명"],
  species: ["전체", "열대어", "해수어", "기수어", "대형어", "기타"],
  board: ["전체", "일상", "추천", "꿀팁", "모임"],
  column: ["전체"],
};
